version: "3.7"

services:
  server:
    build:
      target: production
    ports:
      - 8080:8080
    environment:
      NODE_ENV: "production"

  client:
    build:
      target: production
    ports:
      - 80:80
