version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    depends_on:
      - postgres
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - app-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - app-network

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
