name: build and test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build all
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - name: Client Test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run client
      - name: Server Test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run server
